### ISSUE TITLE
No Image when themening app is active

### ISSUE THREAD

**Issue by tau-ri** [jancborchardt/unsplash#13] opened 2018-03-24 23:44 UTC
Hi,
i have the issue that unsplash is only showing images when the themening APP is disabled.
When the themening is enabled, you can see the image for about a nanosecond appearing in the background if you refresh the loginpage repeating verry verry fast sor several times (like a nervour monkey)..... ;-)

An other NC 13 Server on the same OS base with a similar config hasn't this issue. But, the other server has been updated from NC12 ot NC13. Still workling great....

This is about the server:
Nexcloud Version: **13.0.1 stable**
PHP Version: **7.0.28**
Webserver: **Apache 2.4.18**
OS: **Ubuntu 16.04 lts**

Hope this is enough?
THX, tau'ri

**Comment by jancborchardt** [comment] 2018-03-27 20:15
cc @juliushaertl for theming – I guess by default this should not interfere?

@tau-ri I assume you do _not_ have a background image set in the theming app? Cause then of course it would not work. :)

**Comment by juliushaertl** [comment] 2018-03-28 09:37
> I assume you do not have a background image set in the theming app? Cause then of course it would not work. :)

It is actually the other way round. The theming app adds an `background-image: none !important;` rule to the css if the background image is disabled. So the image from the unsplash app won't appear if the background image is disabled in the theming app.

@tau-ri can you check that?

**Comment by msneet** [comment] 2018-03-30 17:40
I confirm
I have the same thing

**Comment by jancborchardt** [comment] 2018-03-30 17:59
@msneet please also check if you have the background image disabled in your theming app, as @juliushaertl mentioned above. We need some more details here.

**Comment by tau-ri** [comment] 2018-03-30 19:03
Sorry for my late update!
Strange things happen over time...
I just deaktivated the background image and now it's working fine!
Did this before including several tryes to aktivate -> deactivate themening, reinstzaling unsplash and clearing the imagecache with occ commands.

Should update the README markdown and tutorialize this behave....

Thanks for your support!

**Comment by jancborchardt** [comment] 2018-04-03 13:31
@tau-ri so the issue is gone? Or do you have specific steps to reproduce it so we can fix it?

**Comment by tau-ri** [comment] 2018-04-06 08:27
Hi,
I can't repeat all my steps as I somewhen started klicking confused around the system.
 The solution was finally to just delete the background image at aktivated themening app.

THX !

**Comment by jancborchardt** [comment] 2018-04-06 09:47
@msneet do you have the issue still, and can provide reproduction steps so we can fix it?

**Comment by ways** [comment] 2018-04-13 13:43
I have the same problem. I have to choose between unsplash background and having a custom logo. Should this be fixed in the theming app (since it's the one setting no background)?

**Comment by jancborchardt** [comment] 2018-04-13 15:38
@juliushaertl any idea here? @ways @tau-ri further info and steps to reproduce are important.

**Comment by hessercan** [comment] 2018-04-17 08:53
My solution seems simple, vi into the theming.scss file and add a # in front of the background-image: none !important; line. Now I can have my custom logo and cool backgrounds!
![screen shot 2018-04-17 at 4 51 53 am](https://user-images.githubusercontent.com/24305438/38859105-4a04af8a-41fb-11e8-907a-b6ba082fed0b.png)

**Comment by jancborchardt** [comment] 2018-06-23 17:37
@hessercan as you can see from the code, it seems like the issue stems from having used the »Remove background image« function in theming, which makes it display a plain background color. Make sure to »Reset to default« in theming and let me know if the issue still occurs.

**Closed** 2018-08-30 08:32 UTC
Labels: bug, help wanted
