### ISSUE TITLE
Request : customize/enrich the category(ies) in which the Unsplash background are retrieved

### ISSUE THREAD

**Issue by GLLM** [jancborchardt/unsplash#23] opened 2018-06-23 08:58 UTC
Hi all,

at the moment, NC-unsplah retrieves its background pictures from Nature category on unsplash.com

There are many other beautiful categories, such as Clouds, Landscape, Moutain, Sky.

It would be wonderful if the admin could input the categories in which he'd like to see the bg pictures pulled.

What do you think ?
Thanks
GLLM

**Comment by jancborchardt** [comment] 2018-06-23 09:15
This is a duplicate of #4, and might soon be possible through a setting. :)

As of now, you can already edit the URL manually in the CSS file.

**Closed by jancborchardt** 2018-06-23 09:15 UTC

**Comment by GLLM** [comment] 2018-06-23 15:13
Woops sorry !
