### ISSUE TITLE
Request: More categories of images with Unsplash

### ISSUE THREAD

**Issue by geramaya** [jancborchardt/unsplash#45] opened 2019-01-25 21:37 UTC
Hey all,

The bug [#40](https://github.com/jancborchardt/unsplash/issues/40) showed me more images instead of the normal nature photos. My request is to create a configuration option to define more categories for Unsplash.

I like the replacement of:
"...
There is a line:
**background-image : url('https://source.unsplash.com/random/featured/?nature') !important;**
you can change the source of the url there:
**background-image : url('https://source.unsplash.com/1920x1080/ ') !important;**
.."

My personal voting for more configuration options is: yes, do it!

**Comment by newhinton** [comment] 2019-02-10 13:35
this is a duplicate of #4 ;) i will close this for now, but we won't forget this request ;)

**Closed by newhinton** 2019-02-10 13:35 UTC
