### ISSUE TITLE
Possibility to modify the query API  string

### ISSUE THREAD

**Issue by mixim-mixim** [jancborchardt/unsplash#15] opened 2018-04-13 09:28 UTC
May be u should give the possibility to modify the query API  string, so that one can
fix the background for the daily pisture or query only pics from a special collection etc.
Thx in advance ... MiXiM

**Comment by jancborchardt** [comment] 2018-04-13 09:39
This is a duplicate of "Add possibility to customize unsplash url" #4 – contributions welcome. :)

**Closed by jancborchardt** 2018-04-13 09:39 UTC
